// <auto-generated />
using GuildManager.Api.Data;
using GuildManager.Data.GameData.Classes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GuildManager.Api.Migrations
{
    [DbContext(typeof(GuildManagerContext))]
    [Migration("20171208222614_REinit")]
    partial class REinit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GuildManager.Data.GameData.Characters.DbEquipedItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("DbEquipedItems");
                });

            modelBuilder.Entity("GuildManager.Data.GameData.Characters.DbInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("DbInventory");
                });

            modelBuilder.Entity("GuildManager.Data.GameData.Characters.DbPlayerCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClassId");

                    b.Property<int?>("EquipedItemsId");

                    b.Property<int?>("InventoryId");

                    b.Property<string>("Name");

                    b.Property<int?>("RaceId");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("EquipedItemsId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("RaceId");

                    b.ToTable("PlayerCharacters");
                });

            modelBuilder.Entity("GuildManager.Data.GameData.Classes.DbGamelass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BaseResourcesId");

                    b.Property<int?>("BaseStatsId");

                    b.Property<int>("MainStat");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("BaseResourcesId");

                    b.HasIndex("BaseStatsId");

                    b.ToTable("GameClasses");
                });

            modelBuilder.Entity("GuildManager.Data.GameData.Classes.GameClassData.BaseResources", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BaseHealth");

                    b.HasKey("Id");

                    b.ToTable("BaseResources");
                });

            modelBuilder.Entity("GuildManager.Data.GameData.Classes.GameClassData.BaseStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BaseAgility");

                    b.Property<int>("BaseIntelligence");

                    b.Property<int>("BaseStamina");

                    b.Property<int>("BaseStrength");

                    b.Property<int>("BaseWisdom");

                    b.HasKey("Id");

                    b.ToTable("BaseStats");
                });

            modelBuilder.Entity("GuildManager.Data.GameData.Races.DbRace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("DbRace");
                });

            modelBuilder.Entity("GuildManager.Data.GameData.Characters.DbPlayerCharacter", b =>
                {
                    b.HasOne("GuildManager.Data.GameData.Classes.DbGamelass", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GuildManager.Data.GameData.Characters.DbEquipedItems", "EquipedItems")
                        .WithMany()
                        .HasForeignKey("EquipedItemsId");

                    b.HasOne("GuildManager.Data.GameData.Characters.DbInventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId");

                    b.HasOne("GuildManager.Data.GameData.Races.DbRace", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId");
                });

            modelBuilder.Entity("GuildManager.Data.GameData.Classes.DbGamelass", b =>
                {
                    b.HasOne("GuildManager.Data.GameData.Classes.GameClassData.BaseResources", "BaseResources")
                        .WithMany()
                        .HasForeignKey("BaseResourcesId");

                    b.HasOne("GuildManager.Data.GameData.Classes.GameClassData.BaseStats", "BaseStats")
                        .WithMany()
                        .HasForeignKey("BaseStatsId");
                });
#pragma warning restore 612, 618
        }
    }
}
